export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGIN_USER = 'LOGIN_USER';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';

export const EVENTS_FAILURE = "EVENTS_FAILURE";

export const FETCH_FRIENDS_SUCCESS = "FETCH_FRIENDS_SUCCESS";
export const ADD_FRIEND_SUCCESS = "ADD_FRIEND_SUCCESS";

export const FETCH_ALL_FRIENDS_SUCCESS = "FETCH_ALL_FRIENDS_SUCCESS";

export const FACEBOOK_LOGIN = "FACEBOOK_LOGIN";

export const FETCH_EVENTS = "FETCH_EVENTS";
export const CREATE_EVENT = "CREATE_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";
export const FETCH_FRIENDS = "FETCH_FRIENDS";
export const FETCH_ALL_FRIENDS = "FETCH_ALL_FRIENDS";
export const ADD_FRIEND = "ADD_FRIEND";
export const DELETE_FRIEND = "DELETE_FRIEND";
